### PR TITLE
Try

### PR DESCRIPTION
**Pull request by consta35**
Hi Amir,

Can you look over the Mini Linear regression assignment please? I'm not sure how to remove outliers and high leverage points from my data. Do you have any suggestions on where I can go to figure that out please?

Thanks!
Andrea

### CODE REVIEW

**Review by amirziai — CHANGES_REQUESTED** [review]
Never use `import *`. This can have unintended consequences, overwriting your existing functions, variables, or classes.

The idea is to remove high influence points and re-run your regression. Looking at your "influence plot" (`Out[18]`) what would you see these points are? Take a look at the output of `mpp.get_influence().hat_matrix_diag`.

**Comment by consta35** [comment]
what does hat_matrix_diag give me?

So I identify outliers and points of high leverage, so that I can remove them from the bos data set? I am having trouble with the actual mechanics of how this is done. I've figured out how to identify the outliers (In [106]), and can read from the graph the points with the most influence, but don't know how to get those values in a useable form. Once I have the identities of the outliers and the influencing points what is the syntax for removing these points from the original data set?

**Comment by amirziai** [comment]
`hat_matrix_diag` gives you the H leverage values you see in the graph. You can use `np.where` to get the index of observations that are higher than a threshold (e.g. `np.where(...hat_matrix_diag > X`). Once you have those indices you can use `your_dataframe.drop(indices_higher_than_threshold)` to remove the outliers (see [drop](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html)).

You can repeat the exact same process for `get_influence().resid_studentized_external` (remove by a threshold).

**Comment by amirziai** [comment]
Looks pretty good.

Consider using `np.concatenate` to get your `bosclean` dataframe. Here's an example:
https://gist.github.com/amirziai/0a34b67ea20fe99e599b678d20f31a10

**Review by amirziai — APPROVED** [review]

**Pull request merged**
